const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.EventSheet1_Event1_Act1,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.JavaScriptInEvents.EventSheet1_Event2_Act1,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.EventSheet1_Event5_Act2,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.JavaScriptInEvents.сира_Event9_Act1,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.арсений_Event7_Act1,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnMovement
	];
};
self.C3_JsPropNameTable = [
	{Клавиатура: 0},
	{Браузер: 0},
	{Твёрдый: 0},
	{СквознаяПлатформа: 0},
	{Wall: 0},
	{Платформер: 0},
	{Player: 0},
	{ScoreText: 0},
	{Пуля: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Текст2: 0},
	{сердце1: 0},
	{сердце2: 0},
	{сердце3: 0},
	{конец: 0},
	{Текст3: 0},
	{Мышь: 0},
	{СледитьЗа: 0},
	{PlayerHN: 0},
	{Частицы: 0},
	{ТайловыйФон: 0},
	{ТайловыйФон2: 0},
	{Аудио: 0},
	{сираТайловыйФон7: 0},
	{Якорь: 0},
	{сираТайловыйФон6: 0},
	{сираТайловыйФон5: 0},
	{сираТайловыйФон4: 0},
	{сираТайловыйФон3: 0},
	{сираТайловыйФон2: 0},
	{сираТайловыйФон: 0},
	{сираСпрайт3: 0},
	{Синусоида: 0},
	{сираСпрайт2: 0},
	{сираСпрайт: 0},
	{сираМеис: 0},
	{сираЛава67: 0},
	{АРСЕНИЙШипы2: 0},
	{АРСЕНИЙШипы: 0},
	{АРСЕНИЙТекст2: 0},
	{АРСЕНИЙТекст: 0},
	{АРСЕНИЙТайловыйФон3: 0},
	{АРСЕНИЙТайловыйФон2: 0},
	{АРСЕНИЙТайловыйФон: 0},
	{АРСЕНИЙСпрайт5: 0},
	{АРСЕНИЙСпрайт4: 0},
	{АРСЕНИЙСпрайт3: 0},
	{АРСЕНИЙСпрайт2: 0},
	{АРСЕНИЙСпрайт: 0},
	{АРСЕНИЙПол22222222: 0},
	{АРСЕНИЙПол2: 0},
	{АРСЕНИЙПол: 0},
	{АРСЕНИЙОгурец: 0},
	{АРСЕНИЙМонета: 0},
	{АРСЕНИЙВводТекста: 0},
	{АРСЕНИЙБарьер: 0},
	{КЛИМСпрайт: 0},
	{КЛИМСпрайт10: 0},
	{КЛИМСпрайт11: 0},
	{КЛИМСпрайт2: 0},
	{КЛИМСпрайт3: 0},
	{КЛИМСпрайт4: 0},
	{КЛИМСпрайт5: 0},
	{КЛИМСпрайт6: 0},
	{КЛИМСпрайт7: 0},
	{КЛИМСпрайт8: 0},
	{КЛИМСпрайт9: 0},
	{КЛИМТайловыйФон: 0},
	{КЛИМТайловыйФон2: 0},
	{КЛИМТайловыйФон3: 0},
	{ВЛАДСпрайт: 0},
	{ВЛАДСпрайт10: 0},
	{ВЛАДСпрайт11: 0},
	{ВЛАДСпрайт2: 0},
	{ВЛАДСпрайт3: 0},
	{ВЛАДСпрайт4: 0},
	{ВЛАДСпрайт5: 0},
	{ВЛАДСпрайт6: 0},
	{ВЛАДСпрайт7: 0},
	{ВЛАДСпрайт8: 0},
	{ВЛАДСпрайт9: 0},
	{ВЛАДТайловыйФон: 0},
	{Спрайт6: 0},
	{score: 0},
	{hp: 0},
	{rnd: 0},
	{враг: 0},
	{счет: 0}
];

self.InstanceType = {
	Клавиатура: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	Wall: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	сердце1: class extends self.ISpriteInstance {},
	сердце2: class extends self.ISpriteInstance {},
	сердце3: class extends self.ISpriteInstance {},
	конец: class extends self.ISpriteInstance {},
	Текст3: class extends self.ITextInstance {},
	Мышь: class extends self.IInstance {},
	PlayerHN: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Аудио: class extends self.IInstance {},
	сираТайловыйФон7: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон6: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон5: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	сираТайловыйФон: class extends self.ITiledBackgroundInstance {},
	сираСпрайт3: class extends self.ISpriteInstance {},
	сираСпрайт2: class extends self.ISpriteInstance {},
	сираСпрайт: class extends self.ISpriteInstance {},
	сираМеис: class extends self.ITiledBackgroundInstance {},
	сираЛава67: class extends self.ISpriteInstance {},
	АРСЕНИЙШипы2: class extends self.ISpriteInstance {},
	АРСЕНИЙШипы: class extends self.ISpriteInstance {},
	АРСЕНИЙТекст2: class extends self.ITextInstance {},
	АРСЕНИЙТекст: class extends self.ITextInstance {},
	АРСЕНИЙТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	АРСЕНИЙТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	АРСЕНИЙТайловыйФон: class extends self.ITiledBackgroundInstance {},
	АРСЕНИЙСпрайт5: class extends self.ISpriteInstance {},
	АРСЕНИЙСпрайт4: class extends self.ISpriteInstance {},
	АРСЕНИЙСпрайт3: class extends self.ISpriteInstance {},
	АРСЕНИЙСпрайт2: class extends self.ISpriteInstance {},
	АРСЕНИЙСпрайт: class extends self.ISpriteInstance {},
	АРСЕНИЙПол22222222: class extends self.ISpriteInstance {},
	АРСЕНИЙПол2: class extends self.ISpriteInstance {},
	АРСЕНИЙПол: class extends self.ISpriteInstance {},
	АРСЕНИЙОгурец: class extends self.ISpriteInstance {},
	АРСЕНИЙМонета: class extends self.ISpriteInstance {},
	АРСЕНИЙВводТекста: class extends self.ITextInputInstance {},
	АРСЕНИЙБарьер: class extends self.ISpriteInstance {},
	КЛИМСпрайт: class extends self.ISpriteInstance {},
	КЛИМСпрайт10: class extends self.ISpriteInstance {},
	КЛИМСпрайт11: class extends self.ISpriteInstance {},
	КЛИМСпрайт2: class extends self.ISpriteInstance {},
	КЛИМСпрайт3: class extends self.ISpriteInstance {},
	КЛИМСпрайт4: class extends self.ISpriteInstance {},
	КЛИМСпрайт5: class extends self.ISpriteInstance {},
	КЛИМСпрайт6: class extends self.ISpriteInstance {},
	КЛИМСпрайт7: class extends self.ISpriteInstance {},
	КЛИМСпрайт8: class extends self.ISpriteInstance {},
	КЛИМСпрайт9: class extends self.ISpriteInstance {},
	КЛИМТайловыйФон: class extends self.ITiledBackgroundInstance {},
	КЛИМТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	КЛИМТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	ВЛАДСпрайт: class extends self.ISpriteInstance {},
	ВЛАДСпрайт10: class extends self.ISpriteInstance {},
	ВЛАДСпрайт11: class extends self.ISpriteInstance {},
	ВЛАДСпрайт2: class extends self.ISpriteInstance {},
	ВЛАДСпрайт3: class extends self.ISpriteInstance {},
	ВЛАДСпрайт4: class extends self.ISpriteInstance {},
	ВЛАДСпрайт5: class extends self.ISpriteInstance {},
	ВЛАДСпрайт6: class extends self.ISpriteInstance {},
	ВЛАДСпрайт7: class extends self.ISpriteInstance {},
	ВЛАДСпрайт8: class extends self.ISpriteInstance {},
	ВЛАДСпрайт9: class extends self.ISpriteInstance {},
	ВЛАДТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт6: class extends self.ISpriteInstance {}
}